# Generated by Django 4.1.13 on 2024-07-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ej_users", "0012_delete_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="secret_id",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
