# Generated by Django 4.1.13 on 2024-06-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ej_users", "0012_delete_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="secret_id",
            field=models.CharField(
                blank=True, help_text="Unique ID", max_length=128, null=True, unique=True
            ),
        ),
    ]
