# Generated by Django 4.1.13 on 2024-06-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ej_users", "0013_user_secret_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="anonymous",
            field=models.BooleanField(
                default=False, help_text="Anonymous user", verbose_name="Anonymous user"
            ),
        ),
    ]
