# Generated by Django 4.1.13 on 2024-07-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ej_users", "0014_user_is_linked"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_completed_registration",
            field=models.BooleanField(default=True),
        ),
    ]
