# Generated by Django 4.2 on 2024-11-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ej_users", "0016_remove_user_is_linked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="agree_with_privacy_policy",
            field=models.BooleanField(
                default=True,
                help_text="Agree with privacy policy",
                verbose_name="Privacy policy",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="agree_with_terms",
            field=models.BooleanField(
                default=True, help_text="Terms of use", verbose_name="Terms of use"
            ),
        ),
    ]
