# Generated by Django 4.1.13 on 2024-04-03 23:21

from django.db import migrations, models
import ej_conversations.validators


class Migration(migrations.Migration):

    dependencies = [
        ("ej_conversations", "0029_conversation_ending_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="logo_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="conversations/logo/",
                validators=[ej_conversations.validators.validate_file_size],
                verbose_name="Background image",
            ),
        ),
    ]
