# Generated by Django 4.1.13 on 2024-06-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ej_conversations", "0032_remove_vote_analytics_utm"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="participants_can_add_comments",
            field=models.BooleanField(
                default=True,
                help_text="Participants will be able to add comments to this conversation.",
                verbose_name="Participants will be able to add comments to this conversation.",
            ),
        ),
    ]
