# Generated by Django 4.2 on 2024-08-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ej_conversations", "0033_conversation_participants_can_add_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="choice",
            field=models.IntegerField(
                choices=[
                    (None, "(Unknown)"),
                    (0, "Skip"),
                    (1, "Agree"),
                    (-1, "Disagree"),
                ],
                help_text="Agree, disagree or skip",
            ),
        ),
    ]
