# Generated by Django 4.2 on 2024-09-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ej_conversations", "0034_alter_vote_choice"),
        ("ej_conversations", "0034_conversation_send_profile_question_and_more"),
    ]

    operations = []
