# Generated by Django 4.1.13 on 2024-10-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ej_conversations", "0036_alter_comment_rejection_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="choice",
            field=models.IntegerField(
                choices=[(0, "Skip"), (1, "Agree"), (-1, "Disagree")],
                help_text="Agree, disagree or skip",
            ),
        ),
    ]
