# Generated by Django 4.2 on 2024-11-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ej_conversations", "0037_alter_vote_choice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="anonymous_votes_limit",
        ),
        migrations.AddField(
            model_name="conversation",
            name="anonymous_votes",
            field=models.IntegerField(
                default=0,
                help_text="Configures how many anonymous votes the participants can give before asking him to register",
                verbose_name="Number of anonymous votes",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="anonymous_votes_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Check this option if you want your audience to vote without registering. All users will be created with a random and unique ID",
                verbose_name="Enable anonymous votes",
            ),
        ),
    ]
