# Generated by Django 4.2 on 2024-11-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ej_conversations", "0038_remove_conversation_anonymous_votes_limit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="anonymous_votes_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Check this option if you want your audience to vote without registering. All users will be created with a random and unique ID.",
                verbose_name="Enable anonymous votes",
            ),
        ),
    ]
