# Generated by Django 4.2 on 2024-11-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ej_conversations", "0039_alter_conversation_anonymous_votes_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="anonymous_votes",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Configures how many anonymous votes the participants can give before asking him to register",
                verbose_name="Number of anonymous votes",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="anonymous_votes_enabled",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Check this option if you want your audience to vote without registering. All users will be created with a random and unique ID.",
                verbose_name="Enable anonymous votes",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="send_profile_question",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Send a question to participants to complete their profile.",
                verbose_name="Send profile question?",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="votes_to_send_profile_question",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Number of votes to send profile question.",
                verbose_name="Votes to send profile question",
            ),
        ),
    ]
