# Generated by Django 4.2 on 2024-09-30 19:34

from django.db import migrations, models
import ej_clusters.enums


class Migration(migrations.Migration):
    dependencies = [
        ("ej_clusters", "0003_barbara_remove_clusterization_counters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clusterization",
            name="cluster_status",
            field=models.IntegerField(
                default=ej_clusters.enums.ClusterStatus["PENDING_DATA"],
                verbose_name=ej_clusters.enums.ClusterStatus,
            ),
        ),
        migrations.AlterField(
            model_name="stereotypevote",
            name="choice",
            field=models.IntegerField(
                choices=[(None, "(Unknown)"), (0, "Skip"), (1, "Agree"), (-1, "Disagree")]
            ),
        ),
    ]
