# Generated by Django 4.1.13 on 2024-08-17 21:35

from django.db import migrations, models
from ej_profiles.enums import Region


class Migration(migrations.Migration):
    dependencies = [
        ("ej_profiles", "0006_profile_filtered_home_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="region",
            field=models.IntegerField(
                choices=Region.choices,
                default=Region.NOT_FILLED,
                verbose_name="Region",
            ),
        ),
    ]
