# Generated by Django 4.1.13 on 2024-08-17 21:35

import boogie.fields.enum_field
from django.db import migrations
import ej_profiles.enums


class Migration(migrations.Migration):

    dependencies = [
        ("ej_profiles", "0006_profile_filtered_home_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="region",
            field=boogie.fields.enum_field.EnumField(
                ej_profiles.enums.Region,
                default=ej_profiles.enums.Region["NOT_FILLED"],
                verbose_name="Region",
            ),
        ),
    ]
