# Generated by Django 4.1.13 on 2024-08-18 22:13

from django.db import migrations, models
from ej_profiles.enums import AgeRange, Ethnicity


class Migration(migrations.Migration):
    dependencies = [
        ("ej_profiles", "0007_profile_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="age_range",
            field=models.IntegerField(
                choices=AgeRange.choices,
                default=AgeRange.NOT_FILLED,
                verbose_name="Age range",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="ethnicity_choices",
            field=models.IntegerField(
                choices=Ethnicity.choices,
                default=Ethnicity.NOT_FILLED,
                verbose_name="Ethnicity",
            ),
        ),
    ]
