# Generated by Django 4.2 on 2024-09-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ej_profiles", "0008_profile_age_range_profile_ethnicity_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="age_range",
            field=models.IntegerField(
                choices=[
                    (0, "---------"),
                    (7, "refused to answer"),
                    (1, "Less than 17 years"),
                    (2, "Between 17-20 years"),
                    (3, "Between 21-29 years"),
                    (4, "Between 30-45 years"),
                    (5, "Between 45-60 years"),
                    (6, "Over 60 years"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="ethnicity_choices",
            field=models.IntegerField(
                choices=[
                    (0, "---------"),
                    (7, "refused to answer"),
                    (1, "Indigenous"),
                    (2, "Black"),
                    (3, "Brown"),
                    (4, "White"),
                    (5, "Yellow"),
                    (6, "Other"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.IntegerField(
                choices=[
                    (0, "---------"),
                    (5, "refused to answer"),
                    (1, "Female"),
                    (2, "Male"),
                    (3, "Non-binary"),
                    (4, "Other"),
                ],
                default=0,
                verbose_name="Gender identity",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="race",
            field=models.IntegerField(
                choices=[
                    (0, "---------"),
                    (7, "refused to answer"),
                    (1, "Black"),
                    (2, "Brown"),
                    (3, "White"),
                    (4, "Yellow"),
                    (5, "Indigenous"),
                    (6, "Other"),
                ],
                default=0,
                verbose_name="Race",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="region",
            field=models.IntegerField(
                choices=[
                    (0, "---------"),
                    (6, "refused to answer"),
                    (1, "North"),
                    (2, "Northeast"),
                    (3, "Midwest"),
                    (4, "Southeast"),
                    (5, "South"),
                ],
                default=0,
            ),
        ),
    ]
