# Generated by Django 4.2 on 2024-10-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ej_profiles", "0009_alter_profile_age_range_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=16, verbose_name="Phone number"
            ),
        ),
    ]
