# Generated by Django 4.1.13 on 2024-03-12 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ej_integrations", "0003_remove_opinioncomponent_background_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opinioncomponent",
            name="logo_image",
        ),
    ]
