# Generated by Django 4.2 on 2024-10-28 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ej_integrations", "0004_remove_opinioncomponent_logo_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConversationMautic",
        ),
    ]
